version: "3.3"

services:
  web:
    build: .
    volumes:
      - ./logs:/app/logs
    container_name: predictgender_api_container
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
